# Generated by Django 2.0.3 on 2018-03-16 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.CharField(choices=[('CATS', 'Cats'), ('DOGS', 'Dogs'), ('RATS', 'Rats'), ('RACCONS', 'Racoons'), ('BIRDS', 'Birds'), ('PIGEONS', 'Pigeons'), ('REPTILES', 'Reptiles'), ('SNAKES', 'Snakes')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileImg', to='accounts.Clan')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImg',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileImg'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
