# Generated by Django 2.0.3 on 2018-03-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.CharField(choices=[('CATS', 'Cats'), ('DOGS', 'Dogs'), ('RATS', 'Rats'), ('RACCONS', 'Racoons'), ('BIRDS', 'Birds'), ('PIGEONS', 'Pigeons'), ('REPTILES', 'Reptiles'), ('SNAKES', 'Snakes')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profileImg', to='accounts.Clan')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='clan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Clan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileImg'),
        ),
    ]
