# Generated by Django 2.0.1 on 2018-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180604_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimg',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clan',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Clan',
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
