# Generated by Django 2.2.2 on 2019-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('Manhattan', 'Manhattan'), ('Bronx', 'Bronx'), ('Staten Island', 'Staten Island'), ('Greater NYC Area', 'Greater NYC Area'), ('Nowhere', 'Nowhere'), ('The Moon', 'The Moon')], default='Nowhere', max_length=25),
        ),
    ]
