# Generated by Django 2.0.2 on 2018-03-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180311_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileImg'),
        ),
    ]
