# Generated by Django 2.1 on 2018-09-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='primaryImage',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
