# Generated by Django 2.0.1 on 2018-06-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180609_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='url',
        ),
    ]
