# Generated by Django 2.0.1 on 2018-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180609_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
