# Generated by Django 2.0.1 on 2018-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180612_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageCount',
            field=models.IntegerField(default=0),
        ),
    ]
