# Generated by Django 2.1.10 on 2020-02-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20190802_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tag', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False)),
                ('nextBid', models.PositiveIntegerField(default=0)),
                ('activeThreadCount', models.PositiveIntegerField(default=0)),
                ('nsfw', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('bid', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='postImages/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
                ('replyCount', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('imageCount', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('status', models.CharField(choices=[('active', 'active'), ('locked', 'locked'), ('archived', 'archived')], default='active', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='boards.Board')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'thread',
                'verbose_name_plural': 'threads',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Thread'),
        ),
    ]
