# Generated by Django 2.1.10 on 2019-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False),
        ),
    ]
