# Generated by Django 2.2.2 on 2019-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('locked', 'locked'), ('archived', 'archived')], default='active', max_length=20),
        ),
    ]
