# Generated by Django 2.2.2 on 2019-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_thread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='activeThreadCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
