# Generated by Django 2.0.2 on 2018-03-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Stream', max_length=100)),
                ('description', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('live', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('viewers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
