# Generated by Django 2.1.10 on 2020-02-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='service',
            field=models.CharField(blank=True, choices=[('Youtube', 'YouTube'), ('Twitch', 'Twitch'), ('Angelthump', 'Angelthump')], max_length=100),
        ),
    ]
