# Generated by Django 2.2.2 on 2019-07-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='bid',
        ),
    ]
