# Generated by Django 2.0.2 on 2018-02-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('name',), 'verbose_name': 'board', 'verbose_name_plural': 'boards'},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='abbreviation',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='numberOfImages',
            new_name='imageCount',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='numberOfReplies',
            new_name='replyCount',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='viewCount',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='board',
            name='lastUpdated',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='content',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='image',
        ),
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.Board'),
        ),
    ]
