# Generated by Django 2.2.2 on 2019-08-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_thread_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
