# Generated by Django 2.1 on 2018-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
