# Generated by Django 2.1 on 2018-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180923_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='nextBid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
